---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testargo
spec:
  selector:
    app: nginx
  type: LoadBalancer  # ClusterIP se change kiya
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # browser se access ke liye
